# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mainWindow.ui'
#
# Created: Thu Mar 30 21:45:05 2017
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1975, 1017)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/Resources/Resources/Rafa_icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.mapCanvas = QgsMapCanvas(self.centralwidget)
        self.mapCanvas.setGeometry(QtCore.QRect(520, 50, 1171, 940))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.mapCanvas.setFont(font)
        self.mapCanvas.setStyleSheet(_fromUtf8("border-style: solid;\n"
"border-width:3px;\n"
"border-color: rgb(0, 0, 0);"))
        self.mapCanvas.setObjectName(_fromUtf8("mapCanvas"))
        self.northArrowLabel = QtGui.QLabel(self.mapCanvas)
        self.northArrowLabel.setGeometry(QtCore.QRect(10, 870, 51, 61))
        self.northArrowLabel.setStyleSheet(_fromUtf8("border-width:0px;\n"
""))
        self.northArrowLabel.setFrameShape(QtGui.QFrame.NoFrame)
        self.northArrowLabel.setLineWidth(0)
        self.northArrowLabel.setText(_fromUtf8(""))
        self.northArrowLabel.setPixmap(QtGui.QPixmap(_fromUtf8(":/Resources/Resources/compass.png")))
        self.northArrowLabel.setScaledContents(True)
        self.northArrowLabel.setObjectName(_fromUtf8("northArrowLabel"))
        self.raffaLabel = QtGui.QLabel(self.mapCanvas)
        self.raffaLabel.setGeometry(QtCore.QRect(1070, 790, 91, 141))
        self.raffaLabel.setStyleSheet(_fromUtf8("border-width:0px;\n"
""))
        self.raffaLabel.setFrameShape(QtGui.QFrame.NoFrame)
        self.raffaLabel.setLineWidth(0)
        self.raffaLabel.setText(_fromUtf8(""))
        self.raffaLabel.setPixmap(QtGui.QPixmap(_fromUtf8(":/Resources/Resources/Rafa.png")))
        self.raffaLabel.setScaledContents(True)
        self.raffaLabel.setObjectName(_fromUtf8("raffaLabel"))
        self.inputLabel = QtGui.QLabel(self.centralwidget)
        self.inputLabel.setGeometry(QtCore.QRect(0, 0, 521, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Text Me One"))
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.inputLabel.setFont(font)
        self.inputLabel.setStyleSheet(_fromUtf8("border-style: solid;\n"
"border-width:2px;\n"
"border-color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 170, 0);\n"
""))
        self.inputLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.inputLabel.setObjectName(_fromUtf8("inputLabel"))
        self.layerLabel = QtGui.QLabel(self.centralwidget)
        self.layerLabel.setGeometry(QtCore.QRect(1689, 0, 231, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Text Me One"))
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.layerLabel.setFont(font)
        self.layerLabel.setStyleSheet(_fromUtf8("border-style: solid;\n"
"border-width:2px;\n"
"border-color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 170, 0);\n"
""))
        self.layerLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.layerLabel.setObjectName(_fromUtf8("layerLabel"))
        self.routingInformationLabel = QtGui.QLabel(self.centralwidget)
        self.routingInformationLabel.setGeometry(QtCore.QRect(0, 300, 521, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Text Me One"))
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.routingInformationLabel.setFont(font)
        self.routingInformationLabel.setStyleSheet(_fromUtf8("border-style: solid;\n"
"border-width:2px;\n"
"border-color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 170, 0);\n"
""))
        self.routingInformationLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.routingInformationLabel.setObjectName(_fromUtf8("routingInformationLabel"))
        self.mapLabel = QtGui.QLabel(self.centralwidget)
        self.mapLabel.setGeometry(QtCore.QRect(519, 0, 1171, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Text Me One"))
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.mapLabel.setFont(font)
        self.mapLabel.setStyleSheet(_fromUtf8("border-style: solid;\n"
"border-width:2px;\n"
"border-color: rgb(0, 0, 0);"))
        self.mapLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.mapLabel.setObjectName(_fromUtf8("mapLabel"))
        self.zoomInButton = QtGui.QPushButton(self.centralwidget)
        self.zoomInButton.setGeometry(QtCore.QRect(571, 2, 50, 47))
        self.zoomInButton.setStyleSheet(_fromUtf8("background-color: rgba(85, 255, 255, 120);"))
        self.zoomInButton.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/Resources/Resources/zoom-in.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoomInButton.setIcon(icon1)
        self.zoomInButton.setIconSize(QtCore.QSize(40, 40))
        self.zoomInButton.setCheckable(False)
        self.zoomInButton.setObjectName(_fromUtf8("zoomInButton"))
        self.zoomOutButton = QtGui.QPushButton(self.centralwidget)
        self.zoomOutButton.setGeometry(QtCore.QRect(621, 2, 50, 47))
        self.zoomOutButton.setStyleSheet(_fromUtf8("background-color: rgba(85, 255, 255, 120);"))
        self.zoomOutButton.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/Resources/Resources/zoom-out.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoomOutButton.setIcon(icon2)
        self.zoomOutButton.setIconSize(QtCore.QSize(40, 40))
        self.zoomOutButton.setCheckable(False)
        self.zoomOutButton.setObjectName(_fromUtf8("zoomOutButton"))
        self.panButton = QtGui.QPushButton(self.centralwidget)
        self.panButton.setGeometry(QtCore.QRect(671, 2, 50, 47))
        self.panButton.setStyleSheet(_fromUtf8("background-color: rgba(85, 255, 255, 120);"))
        self.panButton.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/Resources/Resources/pan.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.panButton.setIcon(icon3)
        self.panButton.setIconSize(QtCore.QSize(40, 40))
        self.panButton.setCheckable(True)
        self.panButton.setObjectName(_fromUtf8("panButton"))
        self.infoButton = QtGui.QPushButton(self.centralwidget)
        self.infoButton.setGeometry(QtCore.QRect(721, 2, 50, 47))
        self.infoButton.setStyleSheet(_fromUtf8("background-color: rgba(85, 255, 255, 120);"))
        self.infoButton.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/Resources/Resources/information.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.infoButton.setIcon(icon4)
        self.infoButton.setIconSize(QtCore.QSize(40, 40))
        self.infoButton.setCheckable(True)
        self.infoButton.setObjectName(_fromUtf8("infoButton"))
        self.frame1Label = QtGui.QLabel(self.centralwidget)
        self.frame1Label.setGeometry(QtCore.QRect(1690, 50, 230, 940))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Text Me One"))
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.frame1Label.setFont(font)
        self.frame1Label.setStyleSheet(_fromUtf8("border-style: solid;\n"
"border-width:2px;\n"
"border-color: rgb(0, 0, 0);"))
        self.frame1Label.setText(_fromUtf8(""))
        self.frame1Label.setAlignment(QtCore.Qt.AlignCenter)
        self.frame1Label.setObjectName(_fromUtf8("frame1Label"))
        self.frame2Label = QtGui.QLabel(self.centralwidget)
        self.frame2Label.setGeometry(QtCore.QRect(0, 50, 521, 940))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Text Me One"))
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.frame2Label.setFont(font)
        self.frame2Label.setStyleSheet(_fromUtf8("border-style: solid;\n"
"border-width:2px;\n"
"border-color: rgb(0, 0, 0);"))
        self.frame2Label.setText(_fromUtf8(""))
        self.frame2Label.setAlignment(QtCore.Qt.AlignCenter)
        self.frame2Label.setObjectName(_fromUtf8("frame2Label"))
        self.groupBoxPOI = QtGui.QGroupBox(self.centralwidget)
        self.groupBoxPOI.setGeometry(QtCore.QRect(1700, 300, 211, 321))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(15)
        self.groupBoxPOI.setFont(font)
        self.groupBoxPOI.setObjectName(_fromUtf8("groupBoxPOI"))
        self.information_label = QtGui.QLabel(self.groupBoxPOI)
        self.information_label.setGeometry(QtCore.QRect(190, 51, 16, 16))
        self.information_label.setText(_fromUtf8(""))
        self.information_label.setPixmap(QtGui.QPixmap(_fromUtf8(":/Resources/Resources/information.png")))
        self.information_label.setScaledContents(True)
        self.information_label.setObjectName(_fromUtf8("information_label"))
        self.information_label_2 = QtGui.QLabel(self.groupBoxPOI)
        self.information_label_2.setGeometry(QtCore.QRect(190, 98, 16, 16))
        self.information_label_2.setText(_fromUtf8(""))
        self.information_label_2.setPixmap(QtGui.QPixmap(_fromUtf8(":/Resources/Resources/information.png")))
        self.information_label_2.setScaledContents(True)
        self.information_label_2.setObjectName(_fromUtf8("information_label_2"))
        self.layoutWidget = QtGui.QWidget(self.groupBoxPOI)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 30, 166, 291))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.checkBox_PR = QtGui.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_PR.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/Resources/Resources/P+R.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox_PR.setIcon(icon5)
        self.checkBox_PR.setChecked(True)
        self.checkBox_PR.setObjectName(_fromUtf8("checkBox_PR"))
        self.verticalLayout.addWidget(self.checkBox_PR)
        self.checkBox_Garage = QtGui.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.checkBox_Garage.setFont(font)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/Resources/Resources/park-garage_02.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox_Garage.setIcon(icon6)
        self.checkBox_Garage.setChecked(True)
        self.checkBox_Garage.setObjectName(_fromUtf8("checkBox_Garage"))
        self.verticalLayout.addWidget(self.checkBox_Garage)
        self.checkBox_Train = QtGui.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.checkBox_Train.setFont(font)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/Resources/Resources/train.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox_Train.setIcon(icon7)
        self.checkBox_Train.setChecked(True)
        self.checkBox_Train.setObjectName(_fromUtf8("checkBox_Train"))
        self.verticalLayout.addWidget(self.checkBox_Train)
        self.checkBox_BlueBike = QtGui.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.checkBox_BlueBike.setFont(font)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/Resources/Resources/bicycle.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox_BlueBike.setIcon(icon8)
        self.checkBox_BlueBike.setObjectName(_fromUtf8("checkBox_BlueBike"))
        self.verticalLayout.addWidget(self.checkBox_BlueBike)
        self.checkBox_Cambio = QtGui.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.checkBox_Cambio.setFont(font)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/Resources/Resources/transport_rental_car.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox_Cambio.setIcon(icon9)
        self.checkBox_Cambio.setObjectName(_fromUtf8("checkBox_Cambio"))
        self.verticalLayout.addWidget(self.checkBox_Cambio)
        self.checkBox_Taxi = QtGui.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.checkBox_Taxi.setFont(font)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/Resources/Resources/transport_taxi_rank.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox_Taxi.setIcon(icon10)
        self.checkBox_Taxi.setObjectName(_fromUtf8("checkBox_Taxi"))
        self.verticalLayout.addWidget(self.checkBox_Taxi)
        self.groupBoxZones = QtGui.QGroupBox(self.centralwidget)
        self.groupBoxZones.setGeometry(QtCore.QRect(1700, 630, 211, 191))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.groupBoxZones.setFont(font)
        self.groupBoxZones.setObjectName(_fromUtf8("groupBoxZones"))
        self.layoutWidget1 = QtGui.QWidget(self.groupBoxZones)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 30, 168, 151))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.checkBox_ParkingAreas = QtGui.QCheckBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_ParkingAreas.setFont(font)
        self.checkBox_ParkingAreas.setChecked(False)
        self.checkBox_ParkingAreas.setObjectName(_fromUtf8("checkBox_ParkingAreas"))
        self.verticalLayout_2.addWidget(self.checkBox_ParkingAreas)
        self.checkBox_Circulation = QtGui.QCheckBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_Circulation.setFont(font)
        self.checkBox_Circulation.setObjectName(_fromUtf8("checkBox_Circulation"))
        self.verticalLayout_2.addWidget(self.checkBox_Circulation)
        self.checkBox_Inhabitants = QtGui.QCheckBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_Inhabitants.setFont(font)
        self.checkBox_Inhabitants.setObjectName(_fromUtf8("checkBox_Inhabitants"))
        self.verticalLayout_2.addWidget(self.checkBox_Inhabitants)
        self.information_label_4 = QtGui.QLabel(self.groupBoxZones)
        self.information_label_4.setGeometry(QtCore.QRect(190, 50, 16, 16))
        self.information_label_4.setText(_fromUtf8(""))
        self.information_label_4.setPixmap(QtGui.QPixmap(_fromUtf8(":/Resources/Resources/information.png")))
        self.information_label_4.setScaledContents(True)
        self.information_label_4.setObjectName(_fromUtf8("information_label_4"))
        self.information_label_5 = QtGui.QLabel(self.groupBoxZones)
        self.information_label_5.setGeometry(QtCore.QRect(190, 95, 16, 16))
        self.information_label_5.setText(_fromUtf8(""))
        self.information_label_5.setPixmap(QtGui.QPixmap(_fromUtf8(":/Resources/Resources/information.png")))
        self.information_label_5.setScaledContents(True)
        self.information_label_5.setObjectName(_fromUtf8("information_label_5"))
        self.groupBoxOther = QtGui.QGroupBox(self.centralwidget)
        self.groupBoxOther.setGeometry(QtCore.QRect(1700, 830, 211, 141))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(15)
        self.groupBoxOther.setFont(font)
        self.groupBoxOther.setObjectName(_fromUtf8("groupBoxOther"))
        self.layoutWidget_2 = QtGui.QWidget(self.groupBoxOther)
        self.layoutWidget_2.setGeometry(QtCore.QRect(20, 30, 168, 111))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.checkBox_Info = QtGui.QCheckBox(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_Info.setFont(font)
        self.checkBox_Info.setChecked(True)
        self.checkBox_Info.setObjectName(_fromUtf8("checkBox_Info"))
        self.verticalLayout_3.addWidget(self.checkBox_Info)
        self.checkBox_Ortho = QtGui.QCheckBox(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_Ortho.setFont(font)
        self.checkBox_Ortho.setObjectName(_fromUtf8("checkBox_Ortho"))
        self.verticalLayout_3.addWidget(self.checkBox_Ortho)
        self.information_label_6 = QtGui.QLabel(self.groupBoxOther)
        self.information_label_6.setGeometry(QtCore.QRect(190, 53, 16, 16))
        self.information_label_6.setText(_fromUtf8(""))
        self.information_label_6.setPixmap(QtGui.QPixmap(_fromUtf8(":/Resources/Resources/information.png")))
        self.information_label_6.setScaledContents(True)
        self.information_label_6.setObjectName(_fromUtf8("information_label_6"))
        self.groupBoxInput = QtGui.QGroupBox(self.centralwidget)
        self.groupBoxInput.setGeometry(QtCore.QRect(10, 60, 501, 191))
        self.groupBoxInput.setTitle(_fromUtf8(""))
        self.groupBoxInput.setObjectName(_fromUtf8("groupBoxInput"))
        self.layoutWidget_4 = QtGui.QWidget(self.groupBoxInput)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 60, 471, 41))
        self.layoutWidget_4.setObjectName(_fromUtf8("layoutWidget_4"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_9 = QtGui.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_2.addWidget(self.label_9)
        self.toLineEdit = QtGui.QLineEdit(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.toLineEdit.setFont(font)
        self.toLineEdit.setToolTip(_fromUtf8(""))
        self.toLineEdit.setWhatsThis(_fromUtf8(""))
        self.toLineEdit.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.toLineEdit.setObjectName(_fromUtf8("toLineEdit"))
        self.horizontalLayout_2.addWidget(self.toLineEdit)
        self.toButton = QtGui.QPushButton(self.layoutWidget_4)
        self.toButton.setStyleSheet(_fromUtf8("background-color: rgba(85, 255, 255, 120);"))
        self.toButton.setText(_fromUtf8(""))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/Resources/Resources/cursor.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toButton.setIcon(icon11)
        self.toButton.setIconSize(QtCore.QSize(20, 20))
        self.toButton.setCheckable(True)
        self.toButton.setObjectName(_fromUtf8("toButton"))
        self.horizontalLayout_2.addWidget(self.toButton)
        self.layoutWidget2 = QtGui.QWidget(self.groupBoxInput)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 150, 181, 25))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.durationLabel = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.durationLabel.setFont(font)
        self.durationLabel.setObjectName(_fromUtf8("durationLabel"))
        self.horizontalLayout_4.addWidget(self.durationLabel)
        self.durationComboBox = QtGui.QComboBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.durationComboBox.setFont(font)
        self.durationComboBox.setObjectName(_fromUtf8("durationComboBox"))
        self.durationComboBox.addItem(_fromUtf8(""))
        self.durationComboBox.addItem(_fromUtf8(""))
        self.durationComboBox.addItem(_fromUtf8(""))
        self.durationComboBox.addItem(_fromUtf8(""))
        self.durationComboBox.addItem(_fromUtf8(""))
        self.durationComboBox.addItem(_fromUtf8(""))
        self.durationComboBox.addItem(_fromUtf8(""))
        self.durationComboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.durationComboBox)
        self.layoutWidget3 = QtGui.QWidget(self.groupBoxInput)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 110, 246, 25))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.departureLabel = QtGui.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.departureLabel.setFont(font)
        self.departureLabel.setObjectName(_fromUtf8("departureLabel"))
        self.horizontalLayout_3.addWidget(self.departureLabel)
        self.dateTimeEdit = QtGui.QDateTimeEdit(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.dateTimeEdit.setFont(font)
        self.dateTimeEdit.setWrapping(False)
        self.dateTimeEdit.setFrame(True)
        self.dateTimeEdit.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.dateTimeEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2017, 3, 21), QtCore.QTime(10, 0, 0)))
        self.dateTimeEdit.setTime(QtCore.QTime(10, 0, 0))
        self.dateTimeEdit.setCalendarPopup(True)
        self.dateTimeEdit.setObjectName(_fromUtf8("dateTimeEdit"))
        self.horizontalLayout_3.addWidget(self.dateTimeEdit)
        self.layoutWidget4 = QtGui.QWidget(self.groupBoxInput)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 10, 471, 41))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.fromLabel = QtGui.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.fromLabel.setFont(font)
        self.fromLabel.setObjectName(_fromUtf8("fromLabel"))
        self.horizontalLayout.addWidget(self.fromLabel)
        self.fromLineEdit = QtGui.QLineEdit(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.fromLineEdit.setFont(font)
        self.fromLineEdit.setToolTip(_fromUtf8(""))
        self.fromLineEdit.setWhatsThis(_fromUtf8(""))
        self.fromLineEdit.setObjectName(_fromUtf8("fromLineEdit"))
        self.horizontalLayout.addWidget(self.fromLineEdit)
        self.fromButton = QtGui.QPushButton(self.layoutWidget4)
        self.fromButton.setStyleSheet(_fromUtf8("background-color: rgba(85, 255, 255, 120);"))
        self.fromButton.setText(_fromUtf8(""))
        self.fromButton.setIcon(icon11)
        self.fromButton.setIconSize(QtCore.QSize(20, 20))
        self.fromButton.setCheckable(True)
        self.fromButton.setObjectName(_fromUtf8("fromButton"))
        self.horizontalLayout.addWidget(self.fromButton)
        self.calcButton = QtGui.QPushButton(self.centralwidget)
        self.calcButton.setGeometry(QtCore.QRect(102, 260, 231, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.calcButton.setFont(font)
        self.calcButton.setStyleSheet(_fromUtf8("background-color: rgba(85, 255, 255, 120);"))
        self.calcButton.setObjectName(_fromUtf8("calcButton"))
        self.resetButton = QtGui.QPushButton(self.centralwidget)
        self.resetButton.setGeometry(QtCore.QRect(360, 260, 131, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.resetButton.setFont(font)
        self.resetButton.setObjectName(_fromUtf8("resetButton"))
        self.extentButton = QtGui.QPushButton(self.centralwidget)
        self.extentButton.setGeometry(QtCore.QRect(521, 2, 50, 47))
        self.extentButton.setStyleSheet(_fromUtf8("background-color: rgba(85, 255, 255, 120);"))
        self.extentButton.setText(_fromUtf8(""))
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/Resources/Resources/extent.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.extentButton.setIcon(icon12)
        self.extentButton.setIconSize(QtCore.QSize(40, 40))
        self.extentButton.setCheckable(False)
        self.extentButton.setObjectName(_fromUtf8("extentButton"))
        self.scaleLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.scaleLineEdit.setGeometry(QtCore.QRect(1438, 1, 251, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.scaleLineEdit.setFont(font)
        self.scaleLineEdit.setStyleSheet(_fromUtf8("border-style: solid;\n"
"border-width:1px;\n"
"border-color: rgb(0, 0, 0);\n"
"background-color: rgba(85, 255, 255, 120);"))
        self.scaleLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.scaleLineEdit.setReadOnly(True)
        self.scaleLineEdit.setObjectName(_fromUtf8("scaleLineEdit"))
        self.coordinateLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.coordinateLineEdit.setGeometry(QtCore.QRect(1438, 25, 251, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.coordinateLineEdit.setFont(font)
        self.coordinateLineEdit.setStyleSheet(_fromUtf8("border-style: solid;\n"
"border-width:1px;\n"
"border-color: rgb(0, 0, 0);\n"
"background-color: rgba(85, 255, 255, 120);"))
        self.coordinateLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.coordinateLineEdit.setReadOnly(True)
        self.coordinateLineEdit.setObjectName(_fromUtf8("coordinateLineEdit"))
        self.routePRLabel = QtGui.QLabel(self.centralwidget)
        self.routePRLabel.setGeometry(QtCore.QRect(2, 359, 517, 202))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.routePRLabel.setFont(font)
        self.routePRLabel.setStyleSheet(_fromUtf8("border-style: solid;\n"
"border-width:1px;\n"
"border-color: rgb(0, 170, 0);\n"
"background-color: rgba(0, 170, 0, 60);\n"
""))
        self.routePRLabel.setText(_fromUtf8(""))
        self.routePRLabel.setTextFormat(QtCore.Qt.PlainText)
        self.routePRLabel.setObjectName(_fromUtf8("routePRLabel"))
        self.routeStreetLabel = QtGui.QLabel(self.centralwidget)
        self.routeStreetLabel.setGeometry(QtCore.QRect(2, 777, 517, 202))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.routeStreetLabel.setFont(font)
        self.routeStreetLabel.setStyleSheet(_fromUtf8("border-style: solid;\n"
"border-width:1px;\n"
"border-color: rgb(255, 0,0, 100);\n"
"background-color: rgba(255, 0, 0, 50);"))
        self.routeStreetLabel.setText(_fromUtf8(""))
        self.routeStreetLabel.setTextFormat(QtCore.Qt.PlainText)
        self.routeStreetLabel.setObjectName(_fromUtf8("routeStreetLabel"))
        self.routeGarageLabel = QtGui.QLabel(self.centralwidget)
        self.routeGarageLabel.setGeometry(QtCore.QRect(2, 568, 517, 202))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.routeGarageLabel.setFont(font)
        self.routeGarageLabel.setStyleSheet(_fromUtf8("border-style: solid;\n"
"border-width:1px;\n"
"border-color: rgb(0, 170, 255);\n"
"background-color: rgba(0, 170, 255, 70);\n"
""))
        self.routeGarageLabel.setText(_fromUtf8(""))
        self.routeGarageLabel.setTextFormat(QtCore.Qt.PlainText)
        self.routeGarageLabel.setObjectName(_fromUtf8("routeGarageLabel"))
        self.routePRLabel_2 = QtGui.QLabel(self.centralwidget)
        self.routePRLabel_2.setGeometry(QtCore.QRect(2, 359, 517, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.routePRLabel_2.setFont(font)
        self.routePRLabel_2.setStyleSheet(_fromUtf8("border-style: solid;\n"
"font: 75 12pt \"Arial\";\n"
"border-width:1px;\n"
"border-color: rgb(0, 170, 0);\n"
"background-color: rgba(0, 170, 0, 60);\n"
""))
        self.routePRLabel_2.setTextFormat(QtCore.Qt.PlainText)
        self.routePRLabel_2.setObjectName(_fromUtf8("routePRLabel_2"))
        self.routePRLabel_3 = QtGui.QLabel(self.centralwidget)
        self.routePRLabel_3.setGeometry(QtCore.QRect(2, 568, 517, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(13)
        self.routePRLabel_3.setFont(font)
        self.routePRLabel_3.setStyleSheet(_fromUtf8("border-style: solid;\n"
"border-width:1px;\n"
"border-color: rgb(0, 170, 255);\n"
"background-color: rgba(0, 170, 255, 70);\n"
""))
        self.routePRLabel_3.setTextFormat(QtCore.Qt.PlainText)
        self.routePRLabel_3.setObjectName(_fromUtf8("routePRLabel_3"))
        self.routePRLabel_4 = QtGui.QLabel(self.centralwidget)
        self.routePRLabel_4.setGeometry(QtCore.QRect(2, 777, 517, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(13)
        self.routePRLabel_4.setFont(font)
        self.routePRLabel_4.setStyleSheet(_fromUtf8("border-style: solid;\n"
"border-width:1px;\n"
"border-color: rgb(255, 0,0, 100);\n"
"background-color: rgba(255, 0, 0, 50);"))
        self.routePRLabel_4.setTextFormat(QtCore.Qt.PlainText)
        self.routePRLabel_4.setObjectName(_fromUtf8("routePRLabel_4"))
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(1692, 274, 226, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.routeLabel_pr_info1 = QtGui.QLabel(self.centralwidget)
        self.routeLabel_pr_info1.setGeometry(QtCore.QRect(25, 390, 271, 121))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.routeLabel_pr_info1.setFont(font)
        self.routeLabel_pr_info1.setText(_fromUtf8(""))
        self.routeLabel_pr_info1.setObjectName(_fromUtf8("routeLabel_pr_info1"))
        self.routeLabel_pr_info2 = QtGui.QLabel(self.centralwidget)
        self.routeLabel_pr_info2.setGeometry(QtCore.QRect(320, 390, 191, 161))
        self.routeLabel_pr_info2.setText(_fromUtf8(""))
        self.routeLabel_pr_info2.setObjectName(_fromUtf8("routeLabel_pr_info2"))
        self.routeLabel_info2_2 = QtGui.QLabel(self.centralwidget)
        self.routeLabel_info2_2.setGeometry(QtCore.QRect(330, 440, 41, 41))
        self.routeLabel_info2_2.setText(_fromUtf8(""))
        self.routeLabel_info2_2.setPixmap(QtGui.QPixmap(_fromUtf8(":/Resources/Resources/car.png")))
        self.routeLabel_info2_2.setScaledContents(True)
        self.routeLabel_info2_2.setObjectName(_fromUtf8("routeLabel_info2_2"))
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(300, 380, 20, 181))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.routeLabel_g_info1 = QtGui.QLabel(self.centralwidget)
        self.routeLabel_g_info1.setGeometry(QtCore.QRect(25, 600, 271, 121))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.routeLabel_g_info1.setFont(font)
        self.routeLabel_g_info1.setText(_fromUtf8(""))
        self.routeLabel_g_info1.setObjectName(_fromUtf8("routeLabel_g_info1"))
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(300, 589, 20, 181))
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.routeLabel_g_info2 = QtGui.QLabel(self.centralwidget)
        self.routeLabel_g_info2.setGeometry(QtCore.QRect(320, 600, 191, 158))
        self.routeLabel_g_info2.setText(_fromUtf8(""))
        self.routeLabel_g_info2.setObjectName(_fromUtf8("routeLabel_g_info2"))
        self.routeLabel_s_info1 = QtGui.QLabel(self.centralwidget)
        self.routeLabel_s_info1.setGeometry(QtCore.QRect(25, 810, 271, 121))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.routeLabel_s_info1.setFont(font)
        self.routeLabel_s_info1.setText(_fromUtf8(""))
        self.routeLabel_s_info1.setObjectName(_fromUtf8("routeLabel_s_info1"))
        self.line_4 = QtGui.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(300, 798, 20, 181))
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.routeLabel_s_info1_2 = QtGui.QLabel(self.centralwidget)
        self.routeLabel_s_info1_2.setGeometry(QtCore.QRect(320, 810, 191, 158))
        self.routeLabel_s_info1_2.setText(_fromUtf8(""))
        self.routeLabel_s_info1_2.setObjectName(_fromUtf8("routeLabel_s_info1_2"))
        self.routeLabel_info2_5 = QtGui.QLabel(self.centralwidget)
        self.routeLabel_info2_5.setGeometry(QtCore.QRect(330, 497, 41, 41))
        self.routeLabel_info2_5.setText(_fromUtf8(""))
        self.routeLabel_info2_5.setPixmap(QtGui.QPixmap(_fromUtf8(":/Resources/Resources/bicycle.svg")))
        self.routeLabel_info2_5.setScaledContents(True)
        self.routeLabel_info2_5.setObjectName(_fromUtf8("routeLabel_info2_5"))
        self.routeLabel_info2_6 = QtGui.QLabel(self.centralwidget)
        self.routeLabel_info2_6.setGeometry(QtCore.QRect(330, 710, 38, 33))
        self.routeLabel_info2_6.setText(_fromUtf8(""))
        self.routeLabel_info2_6.setPixmap(QtGui.QPixmap(_fromUtf8(":/Resources/Resources/walking_03.png")))
        self.routeLabel_info2_6.setScaledContents(True)
        self.routeLabel_info2_6.setObjectName(_fromUtf8("routeLabel_info2_6"))
        self.routeLabel_pr_totallength = QtGui.QLabel(self.centralwidget)
        self.routeLabel_pr_totallength.setGeometry(QtCore.QRect(330, 400, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.routeLabel_pr_totallength.setFont(font)
        self.routeLabel_pr_totallength.setObjectName(_fromUtf8("routeLabel_pr_totallength"))
        self.routeLabel_pr_car = QtGui.QLabel(self.centralwidget)
        self.routeLabel_pr_car.setGeometry(QtCore.QRect(400, 450, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.routeLabel_pr_car.setFont(font)
        self.routeLabel_pr_car.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.routeLabel_pr_car.setObjectName(_fromUtf8("routeLabel_pr_car"))
        self.routeLabel_pr_bike = QtGui.QLabel(self.centralwidget)
        self.routeLabel_pr_bike.setGeometry(QtCore.QRect(400, 510, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.routeLabel_pr_bike.setFont(font)
        self.routeLabel_pr_bike.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.routeLabel_pr_bike.setObjectName(_fromUtf8("routeLabel_pr_bike"))
        self.routeLabel_g_walk = QtGui.QLabel(self.centralwidget)
        self.routeLabel_g_walk.setGeometry(QtCore.QRect(400, 720, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.routeLabel_g_walk.setFont(font)
        self.routeLabel_g_walk.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.routeLabel_g_walk.setObjectName(_fromUtf8("routeLabel_g_walk"))
        self.routeLabel_g_car = QtGui.QLabel(self.centralwidget)
        self.routeLabel_g_car.setGeometry(QtCore.QRect(400, 660, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.routeLabel_g_car.setFont(font)
        self.routeLabel_g_car.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.routeLabel_g_car.setObjectName(_fromUtf8("routeLabel_g_car"))
        self.routeLabel_info2_8 = QtGui.QLabel(self.centralwidget)
        self.routeLabel_info2_8.setGeometry(QtCore.QRect(330, 650, 41, 41))
        self.routeLabel_info2_8.setText(_fromUtf8(""))
        self.routeLabel_info2_8.setPixmap(QtGui.QPixmap(_fromUtf8(":/Resources/Resources/car.png")))
        self.routeLabel_info2_8.setScaledContents(True)
        self.routeLabel_info2_8.setObjectName(_fromUtf8("routeLabel_info2_8"))
        self.routeLabel_g_totallength = QtGui.QLabel(self.centralwidget)
        self.routeLabel_g_totallength.setGeometry(QtCore.QRect(330, 610, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.routeLabel_g_totallength.setFont(font)
        self.routeLabel_g_totallength.setObjectName(_fromUtf8("routeLabel_g_totallength"))
        self.routeLabel_info2_4 = QtGui.QLabel(self.centralwidget)
        self.routeLabel_info2_4.setGeometry(QtCore.QRect(330, 860, 41, 41))
        self.routeLabel_info2_4.setText(_fromUtf8(""))
        self.routeLabel_info2_4.setPixmap(QtGui.QPixmap(_fromUtf8(":/Resources/Resources/car.png")))
        self.routeLabel_info2_4.setScaledContents(True)
        self.routeLabel_info2_4.setObjectName(_fromUtf8("routeLabel_info2_4"))
        self.routeLabel_s_walk = QtGui.QLabel(self.centralwidget)
        self.routeLabel_s_walk.setGeometry(QtCore.QRect(400, 930, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.routeLabel_s_walk.setFont(font)
        self.routeLabel_s_walk.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.routeLabel_s_walk.setObjectName(_fromUtf8("routeLabel_s_walk"))
        self.routeLabel_s_car = QtGui.QLabel(self.centralwidget)
        self.routeLabel_s_car.setGeometry(QtCore.QRect(400, 870, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.routeLabel_s_car.setFont(font)
        self.routeLabel_s_car.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.routeLabel_s_car.setObjectName(_fromUtf8("routeLabel_s_car"))
        self.routeLabel_info2_7 = QtGui.QLabel(self.centralwidget)
        self.routeLabel_info2_7.setGeometry(QtCore.QRect(330, 920, 38, 33))
        self.routeLabel_info2_7.setText(_fromUtf8(""))
        self.routeLabel_info2_7.setPixmap(QtGui.QPixmap(_fromUtf8(":/Resources/Resources/walking_03.png")))
        self.routeLabel_info2_7.setScaledContents(True)
        self.routeLabel_info2_7.setObjectName(_fromUtf8("routeLabel_info2_7"))
        self.routeLabel_s_totallength = QtGui.QLabel(self.centralwidget)
        self.routeLabel_s_totallength.setGeometry(QtCore.QRect(330, 820, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.routeLabel_s_totallength.setFont(font)
        self.routeLabel_s_totallength.setObjectName(_fromUtf8("routeLabel_s_totallength"))
        self.routeLabel_export_pr = QtGui.QPushButton(self.centralwidget)
        self.routeLabel_export_pr.setGeometry(QtCore.QRect(25, 524, 131, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.routeLabel_export_pr.setFont(font)
        self.routeLabel_export_pr.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.routeLabel_export_pr.setStyleSheet(_fromUtf8(""))
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/Resources/Resources/Google_Earth_Icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.routeLabel_export_pr.setIcon(icon13)
        self.routeLabel_export_pr.setObjectName(_fromUtf8("routeLabel_export_pr"))
        self.routeLabel_export_g = QtGui.QPushButton(self.centralwidget)
        self.routeLabel_export_g.setGeometry(QtCore.QRect(25, 734, 131, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.routeLabel_export_g.setFont(font)
        self.routeLabel_export_g.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.routeLabel_export_g.setIcon(icon13)
        self.routeLabel_export_g.setObjectName(_fromUtf8("routeLabel_export_g"))
        self.routeLabel_export_s = QtGui.QPushButton(self.centralwidget)
        self.routeLabel_export_s.setGeometry(QtCore.QRect(25, 944, 131, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.routeLabel_export_s.setFont(font)
        self.routeLabel_export_s.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.routeLabel_export_s.setIcon(icon13)
        self.routeLabel_export_s.setObjectName(_fromUtf8("routeLabel_export_s"))
        self.groupBoxRoutingLayers = QtGui.QGroupBox(self.centralwidget)
        self.groupBoxRoutingLayers.setGeometry(QtCore.QRect(1700, 70, 211, 195))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(15)
        self.groupBoxRoutingLayers.setFont(font)
        self.groupBoxRoutingLayers.setObjectName(_fromUtf8("groupBoxRoutingLayers"))
        self.layoutWidget_3 = QtGui.QWidget(self.groupBoxRoutingLayers)
        self.layoutWidget_3.setGeometry(QtCore.QRect(20, 20, 168, 181))
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.checkBox_RoutePR = QtGui.QCheckBox(self.layoutWidget_3)
        self.checkBox_RoutePR.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        self.checkBox_RoutePR.setFont(font)
        self.checkBox_RoutePR.setStyleSheet(_fromUtf8("color: rgb(0, 170, 0);"))
        self.checkBox_RoutePR.setObjectName(_fromUtf8("checkBox_RoutePR"))
        self.verticalLayout_4.addWidget(self.checkBox_RoutePR)
        self.checkBox_RouteGarage = QtGui.QCheckBox(self.layoutWidget_3)
        self.checkBox_RouteGarage.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        self.checkBox_RouteGarage.setFont(font)
        self.checkBox_RouteGarage.setStyleSheet(_fromUtf8("color: rgb(0, 100, 255);"))
        self.checkBox_RouteGarage.setObjectName(_fromUtf8("checkBox_RouteGarage"))
        self.verticalLayout_4.addWidget(self.checkBox_RouteGarage)
        self.checkBox_RouteStreet = QtGui.QCheckBox(self.layoutWidget_3)
        self.checkBox_RouteStreet.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        self.checkBox_RouteStreet.setFont(font)
        self.checkBox_RouteStreet.setStyleSheet(_fromUtf8("color: rgba(255, 0, 0, 210);"))
        self.checkBox_RouteStreet.setObjectName(_fromUtf8("checkBox_RouteStreet"))
        self.verticalLayout_4.addWidget(self.checkBox_RouteStreet)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MySpot.Gent", None))
        self.inputLabel.setText(_translate("MainWindow", "INPUT", None))
        self.layerLabel.setText(_translate("MainWindow", "LAYERS", None))
        self.routingInformationLabel.setText(_translate("MainWindow", "ROUTING INFORMATION", None))
        self.mapLabel.setText(_translate("MainWindow", "MAP", None))
        self.groupBoxPOI.setTitle(_translate("MainWindow", "POI", None))
        self.checkBox_PR.setText(_translate("MainWindow", "P+R    ", None))
        self.checkBox_Garage.setText(_translate("MainWindow", "Parking Garages", None))
        self.checkBox_Train.setText(_translate("MainWindow", "Train Stations", None))
        self.checkBox_BlueBike.setText(_translate("MainWindow", "Blue Bike", None))
        self.checkBox_Cambio.setText(_translate("MainWindow", "Cambio", None))
        self.checkBox_Taxi.setText(_translate("MainWindow", "Taxi", None))
        self.groupBoxZones.setTitle(_translate("MainWindow", "Zones", None))
        self.checkBox_ParkingAreas.setText(_translate("MainWindow", "Parking Area\'s", None))
        self.checkBox_Circulation.setText(_translate("MainWindow", "Circulation Plan", None))
        self.checkBox_Inhabitants.setText(_translate("MainWindow", "Inhabitants", None))
        self.groupBoxOther.setTitle(_translate("MainWindow", "Other", None))
        self.checkBox_Info.setText(_translate("MainWindow", "Information", None))
        self.checkBox_Ortho.setText(_translate("MainWindow", "Ortho", None))
        self.label_9.setText(_translate("MainWindow", "To:     ", None))
        self.toLineEdit.setPlaceholderText(_translate("MainWindow", "\'X-coordinate\' , \'Y-coordinate\'", None))
        self.durationLabel.setText(_translate("MainWindow", "Duration:", None))
        self.durationComboBox.setItemText(0, _translate("MainWindow", "15 -30 min", None))
        self.durationComboBox.setItemText(1, _translate("MainWindow", "1 h", None))
        self.durationComboBox.setItemText(2, _translate("MainWindow", "2 h", None))
        self.durationComboBox.setItemText(3, _translate("MainWindow", "3 h", None))
        self.durationComboBox.setItemText(4, _translate("MainWindow", "4 h", None))
        self.durationComboBox.setItemText(5, _translate("MainWindow", "5 h", None))
        self.durationComboBox.setItemText(6, _translate("MainWindow", "6 h", None))
        self.durationComboBox.setItemText(7, _translate("MainWindow", "24 h", None))
        self.departureLabel.setText(_translate("MainWindow", "Departure:", None))
        self.fromLabel.setText(_translate("MainWindow", "From:", None))
        self.fromLineEdit.setPlaceholderText(_translate("MainWindow", "\'X-coordinate\' , \'Y-coordinate\'", None))
        self.calcButton.setText(_translate("MainWindow", "Calculate Route", None))
        self.resetButton.setText(_translate("MainWindow", "Reset", None))
        self.routePRLabel_2.setText(_translate("MainWindow", "  P + R - Info", None))
        self.routePRLabel_3.setText(_translate("MainWindow", "  Garage - Info", None))
        self.routePRLabel_4.setText(_translate("MainWindow", "  Street - Info", None))
        self.routeLabel_pr_totallength.setText(_translate("MainWindow", "TextLabel", None))
        self.routeLabel_pr_car.setText(_translate("MainWindow", "TextLabel", None))
        self.routeLabel_pr_bike.setText(_translate("MainWindow", "TextLabel", None))
        self.routeLabel_g_walk.setText(_translate("MainWindow", "TextLabel", None))
        self.routeLabel_g_car.setText(_translate("MainWindow", "TextLabel", None))
        self.routeLabel_g_totallength.setText(_translate("MainWindow", "TextLabel", None))
        self.routeLabel_s_walk.setText(_translate("MainWindow", "TextLabel", None))
        self.routeLabel_s_car.setText(_translate("MainWindow", "TextLabel", None))
        self.routeLabel_s_totallength.setText(_translate("MainWindow", "TextLabel", None))
        self.routeLabel_export_pr.setText(_translate("MainWindow", "Export to KML", None))
        self.routeLabel_export_g.setText(_translate("MainWindow", "Export to KML", None))
        self.routeLabel_export_s.setText(_translate("MainWindow", "Export to KML", None))
        self.groupBoxRoutingLayers.setTitle(_translate("MainWindow", "Routing Layers", None))
        self.checkBox_RoutePR.setText(_translate("MainWindow", "Route P+R", None))
        self.checkBox_RouteGarage.setText(_translate("MainWindow", "Route Garage", None))
        self.checkBox_RouteStreet.setText(_translate("MainWindow", "Route Street", None))

from qgis.gui import QgsMapCanvas
import resources_rc
